config/routes.rb
Rails.application.routes.draw do
  get 'buyer/index'

  get 'buyer/new'

  get 'buyer/create'

  get 'buyer/edit'

  get 'buyer/update'

  get 'buyer/destroy'

  get 'usr_vender/registration'

  get 'usr_vender/index'

  root 'usr#index'
  # get 'usr/index'
  #
  # get 'usr/register'

  #devise_for :usr_contacts





  devise_for :usr_contacts, :controllers => { registrations: 'registrations' }
  #devise_for :contacts
  # devise_scope :contacts do
  #   #@request.env["devise.mapping"] = Devise.mappings[:users]
  #   match '/users/index', to: 'devise/sessions#new', via: :get
  #   get 'users/index' => "users"
  #   get 'users/register'
  # end

  devise_scope :usr_contacts do
    get '/usr/index' => "usr#index"
    get '/usr/register' => "usr#register"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/usr_buyer.rb
class UsrBuyer < ApplicationRecord
  has_one :usr_contact
end

app/models/usr_contact.rb
class UsrContact < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :image, UsrContactUploader

  # validations for sing in
  validates :name, :presence => true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  validate :password_complexity
  def password_complexity
    if password.present? and not password.match(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)./)
      errors.add :password, "must include at least one lowercase letter, one uppercase letter, and one digit"
    end
  end
  has_and_belongs_to_many :usr_vender_properties
  has_one :usr_buyer
end

app/models/usr_contact_vender.rb
class UsrContactVender < ApplicationRecord
  belongs_to :UsrContact
  belongs_to :UsrVenderProperty
end

app/models/usr_vender_property.rb
class UsrVenderProperty < ApplicationRecord
  has_and_belongs_to_many :usr_contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  private
  def after_sign_in_path_for(resource)
    root_path
  end



  # private
  # def after_sign_in_path_for(resource)
  #  #if session[:userType].nil?
  #
  #  # if Rails.application.config.session_store key:'userType' == "sellert"
  #   #if cookies[:userType] == "seller"
  #   if session[:userType]=='sellerZ'
  #     usr_register_path
  #   else
  #     root_path
  #   end
  # end
end

app/controllers/buyer_controller.rb
class BuyerController < ApplicationController
  def index
  end

  def new
    @buyer = UsrBuyer.new
  end

  def create
    @currentuser = current_user
    @buyer = UsrBuyer.new(buyer_params)
    @currentuser.usr_buyer = @buyer
    if @buyer.save()
      redirect_to root_path, notice: "The buyer has been registered."
    else
      redirect_to root_path, notice: "The buyer has not been registered."
    end

  end

  def edit
    @currentuserid = current_user.id
    @buyer = UsrBuyer.find(usr_contact_id = @currentuserid)
  end

  def update
    @currentuserid = current_user.id
    @buyer = UsrBuyer.find(usr_contact_id = @currentuserid)
    if @buyer.update_attributes(buyer_params)
      redirect_to root_path, notice:  "The buyer has been updated"
    else
      redirect_to root_path, notice:  "The buyer has not been updated"
    end


  end

  def destroy

  end

  private
  def buyer_params
    params.require(:usr_buyer).permit(:addressLine1, :addressLine2, :addressLine3, :city, :zipCode, :country, :dob, :anniversary )
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:usr_contact).permit(:name, :mobile, :email, :password, :password_confirmation, :image)
  end

  def account_update_params
    params.require(:usr_contact).permit(:name, :mobile, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/usr_controller.rb
class UsrController < ApplicationController
  def index
    @cotacts = UsrContact.all # get all registerd contacts
  end

  def register
  end
end

app/controllers/usr_vender_controller.rb
class UsrVenderController < ApplicationController
  def registration
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buyer_helper.rb
module BuyerHelper
end

app/helpers/usr_helper.rb
module UsrHelper
end

app/helpers/usr_vender_helper.rb
module UsrVenderHelper
end

app/views/buyer/_form.html.erb
<div class="form-group">
  Address Line1<%= f.text_field :addressLine1, class: "form-control" %>
</div>
<div class="form-group">
  Address Line2<%= f.text_field :addressLine2, class: "form-control" %>
</div>
<div class="form-group">
  Address Line3<%= f.text_field :addressLine3, class: "form-control" %>
</div>
<div class="form-group">
  City<%= f.text_field :city, class: "form-control" %>
</div>
<div class="form-group">
  Zip Code<%= f.text_field :zipCode, class: "form-control" %>
</div>
<div class="form-group">
  Country<%= f.text_field :country, class: "form-control" %>
</div>
<div class="form-group">
  Date of Birth<%= f.text_field :dob, id: "datepicker", class: "form-control" %>
</div>
<div class="form-group">
  Anniversary Date<%= f.date_select :anniversary, id: "datepicker", class: "form-control" %>
</div>

app/views/buyer/create.html.erb
<h1>Buyers#create</h1>
<p>Find me in app/views/buyers/create.html.erb</p>

app/views/buyer/destroy.html.erb
<h1>Buyers#destroy</h1>
<p>Find me in app/views/buyers/destroy.html.erb</p>

app/views/buyer/edit.html.erb
<div class = "well">
  <%= form_for @buyer, url: buyers_update_path, :method => :POST do |e| %>
      <%= render partial: "buyers/form" , locals: {:f => e} %>

      <%= e.submit "Save", class: "btn-block btn-primary" %>
  <% end %>
</div>

app/views/buyer/index.html.erb
<h1>Buyers#index</h1>
<p>Find me in app/views/buyers/index.html.erb</p>

app/views/buyer/new.html.erb
<div class = "well">
  <%= form_for @buyer, url: {action: "create"} do |e| %>
      <%= render partial: "buyers/form" , locals: {:f => e} %>

      <%= e.submit "Save", class: "btn-block btn-primary" %>
  <% end %>
</div>

app/views/buyer/update.html.erb
<h1>Buyer#update</h1>
<p>Find me in app/views/buyer/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smartmall</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js' %>
  <%= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/jquery-ui.min.js' %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js' %>
</head>

<body>
<nav class="navbar navbar-inverse ">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Smart Mall</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
        <li><%= link_to "Register Items"%></li>
        <li><%= link_to "All Items" %></li>
        <li><%= link_to "Sell", usr_vender_registration_path%></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Login", new_usr_contact_session_path , :class=>'glyphicon glyphicon-log-in'%></li>
        <li><%= link_to "Sign up", new_usr_contact_registration_path , :class=>'glyphicon glyphicon-user'%></li>
        <li><%= link_to "Sign out", destroy_usr_contact_session_path, method: :delete%></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>
<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>
</body>
</html>

app/views/usr/index.html.erb
<h3>All users</h3>
<% @cotacts.each do |con| %>
    <p><%= image_tag con.image ,:size => '80x80' %></p>
    <p><%=con.name%></p>
    <p><%=con.email%></p>
    <br/>
<% end %>

app/views/usr/register.html.erb
<h1>Usr#register</h1>
<p>Find me in app/views/usr/register.html.erb</p>

app/views/usr_vender/index.html.erb
<h1>UsrVender#index</h1>
<p>Find me in app/views/usr_vender/index.html.erb</p>

app/views/usr_vender/registration.html.erb
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                document.getElementById("blah").style.display = 'block';
                document.getElementById("uploadarea").style.color = "white";
                $('#blah')
                    .attr('src', e.target.result)
                    .width(400)
                    .height(200);
                document.getElementById("imagedragtxt").style.display = 'none';
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

    var imageLoader = document.getElementById('post_image');
    imageLoader.addEventListener('change', handleImage, false);

    function handleImage(e) {
        var reader = new FileReader();
        reader.onload = function (event) {
            $('.uploader img').attr('src',event.target.result);
        }
        reader.readAsDataURL(e.target.files[0]);
    }

</script>
<style>
  .uploader {
    position:relative;
    overflow:hidden;
    width:auto;
    height:200px;
    background:#f3f3f3;
    border:2px dashed #e8e8e8;
  }

  #post_image{
    position:absolute;
    width:300px;
    height:400px;
    top:-50px;
    left:0;
    z-index:2;
    opacity:0;
    cursor:pointer;
  }

  .uploader img{
    position:absolute;
    width:302px;
    height:352px;
    top:-1px;
    left:-1px;
    z-index:1;
    border:none;
  }
</style>

<h3>Seller details</h3>
<%= form_for :post, url: usr_vender_index_path do |f| %>
    <p>
      <%=f.label :Shop_Name %><br>
      <%=f.text_field :name,{:class => 'form-control'} %>
    </p>

    <p>
      <%=f.label :Specified_Area %><br>
      <%=f.text_field :price,{:class => 'form-control'} %>
    </p>

    <p>
      <%=f.label :Contact_No %><br>
      <%=f.text_field :color,{:class => 'form-control'} %>
    </p>

    <div id="uploadarea" class="uploader" onclick="$('#post_image').click()">
      <div id="imagedragtxt"> click here or drag here your images for preview and set item picture </div>
      <input type="file" name="image"  id="filePhoto" onchange="readURL(this)"  style="display: none"/>
      <%= f.file_field :image, :onchange=>'readURL(this)' %>
      <img id="blah" src="#" alt="image" style="display: none;"/>
    </div>

    <div class="form-group">
      <%= f.submit({:value=>'Register',:class => 'btn btn-primary'})%>
    </div>
<% end %>